language: java
addons:
  sonarcloud:
    organization: cril
    token:
      secure: "T0d7XxtjqJy9RpLArE5LPM0dFdXwnlEn3fRmRlbMNMaxa6CqCN6DOwKelMrdvrBK522xEgJIIBqYFJCLGUcBUMaBqA9lWnBQHOlurkQlKxH/bWAZzrMklmb1+BOVLxFlUO3R4CfkAsESzbZPD+HHzPaVN2uc9Zq1YEm2DefOVSBUIHfCfKpX1Kj4zhGjzz07Yce8kUql9nLFCytAde6WK8hlaVB9tLi3srqq2Qsix+Gg8e+gAONVQDExpWbY4otLUQmdKDt32msHGVAfn++4eLsA/1EsO0k+ycIbFc6TuiDGIgLeZbzK8D1Llb7GZj9wlD9bOkDXd1P/sM3sW2ROrvfmLecjeYfqj/uCq1l40TuVno8pP1qtifb68LLztB6BUWRlOSzxY90PYwuVUB6Mwt5T7vXncpAYastdbbE2gjOaid/QeZnecW4iFHpj1Mg5rjZG3laOOPzOPIJciGZsYLmWoHoTYURwJ2I8irlWxwGLuOcrnJ2DLuiRfLORaZ2FCGDbEVhi9Su+ynkQkF0ZHOx/GinxmiIyAAdhQ5zagiwerOcN8ueHD6CLdlT/x29/5wJr7wzYDNZ4BaqS51QGw0ppdbky7rzdt7FujpEBLDG/9TxNCfrNZkRqGsSM89+frphsomWY1y51QfAf5/xQAUeQIzMwkm/i9wAYpdsD7PU="
jdk:
  - oraclejdk11
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

